import {describe,it,expect} from "vitest";
import {createFakeDataService} from "../data/fake";
import {createFakeAnalyticsService} from "./fake";
import hospital from "../../../metadata/hospital.json" with {type:"json"};
import hotel from "../../../metadata/hotel.json" with {type:"json"};
import type {MetadataStore,RequestContext,AppMetadata} from "@cab/contracts";
const apps={hospital:hospital as AppMetadata,hotel:hotel as AppMetadata};const metadata={getApp:async(ctx:RequestContext)=>apps[ctx.appId as "hospital"|"hotel"]} as MetadataStore;const data=createFakeDataService(),analytics=createFakeAnalyticsService({data,metadata});
const ctx=(appId:string):RequestContext=>({tenantId:"t",appId,userId:"u",role:"admin",sessionId:"s",traceId:"t",now:"2026-10-07"});
describe("analytics service",()=>{
 it("compares MTD usage against matching September dates and flags period lengths",async()=>{const r=await analytics.run(ctx("hospital"),{kind:"period_compare",dataset:"medicine_usage",metric:{field:"quantity",agg:"sum"},dateField:"usage_date",periodA:{token:"this_month"},periodB:{token:"last_month_to_date"},breakdownBy:["medicine"],where:[]});expect(r.periods?.a.days).toBe(7);expect(r.periods?.b.days).toBe(7);expect(r.periods?.a.value).toBe(1980);expect(r.periods?.b.value).toBe(1923);expect(r.pctChange).toBeCloseTo(57/1923,8);expect(r.breakdown?.reduce((s,x)=>s+x.a,0)).toBe(r.periods?.a.value);});
 it("recognizes Amoxicillin increase and stable Insulin",async()=>{const base={kind:"period_compare" as const,dataset:"medicine_usage",metric:{field:"quantity",agg:"sum" as const},dateField:"usage_date",periodA:{start:"2026-09-23",end:"2026-10-06"},periodB:{start:"2026-09-09",end:"2026-09-22"},breakdownBy:[],where:[]};const am=await analytics.run(ctx("hospital"),{...base,where:[{field:"medicine",op:"eq",value:"Amoxicillin"}]});const ins=await analytics.run(ctx("hospital"),{...base,where:[{field:"medicine",op:"eq",value:"Insulin"}]});expect(am.periods?.a.value).toBe(204);expect(am.periods?.b.value).toBe(130);expect(am.pctChange).toBeCloseTo(74/130,8);expect(Math.abs(ins.pctChange??0)).toBeLessThan(.1);});
 it("reports hotel monthly revenue and room bookings decrease",async()=>{const run=(category?:string)=>analytics.run(ctx("hotel"),{kind:"period_compare",dataset:"revenue",metric:{field:"amount",agg:"sum"},dateField:"revenue_date",periodA:{start:"2026-09-01",end:"2026-09-30"},periodB:{start:"2026-08-01",end:"2026-08-31"},breakdownBy:[],where:category?[{field:"category",op:"eq",value:category}]:[]});const all=await run(),room=await run("Room Bookings");expect(all.pctChange).toBeLessThan(0);expect(room.pctChange).toBeLessThan(-.1);});
 it("supports trend, rank, baseline empty, and <=2% insufficient evidence",async()=>{const trend=await analytics.run(ctx("hospital"),{kind:"trend",dataset:"medicine_usage",metric:{field:"quantity",agg:"sum"},dateField:"usage_date",grain:"week",period:{token:"last_30_days"},breakdownBy:[],where:[]});expect(trend.series?.length).toBeGreaterThan(1);const rank=await analytics.run(ctx("hospital"),{kind:"rank",dataset:"medicine_usage",metric:{field:"quantity",agg:"sum"},by:"medicine",direction:"desc",limit:3,period:{token:"this_month"},dateField:"usage_date",where:[]});expect(rank.ranking).toHaveLength(3);const empty=await analytics.run(ctx("hospital"),{kind:"period_compare",dataset:"medicine_usage",metric:{field:"quantity",agg:"sum"},dateField:"usage_date",periodA:{start:"2026-10-01",end:"2026-10-07"},periodB:{start:"2025-01-01",end:"2025-01-07"},breakdownBy:[],where:[]});expect(empty.insufficientEvidence).toBe(true);const flat=await analytics.run(ctx("hospital"),{kind:"period_compare",dataset:"medicine_usage",metric:{field:"quantity",agg:"sum"},dateField:"usage_date",periodA:{start:"2026-09-23",end:"2026-10-06"},periodB:{start:"2026-09-09",end:"2026-09-22"},breakdownBy:[],where:[{field:"medicine",op:"eq",value:"Insulin"}]});expect(flat.insufficientEvidence).toBe(true);});
 it("finds OTA cancellation increase and writes a partial-period note when lengths differ",async()=>{const r=await analytics.run(ctx("hotel"),{kind:"period_compare",dataset:"bookings",metric:{field:"booking_id",agg:"count"},dateField:"check_in",periodA:{start:"2026-09-01",end:"2026-09-30"},periodB:{start:"2026-08-01",end:"2026-08-31"},breakdownBy:[],where:[{field:"channel",op:"eq",value:"OTA"},{field:"status",op:"eq",value:"Cancelled"}]});expect(r.periods?.a.value).toBeGreaterThan(0);expect(r.pctChange).toBeGreaterThan(0);const partial=await analytics.run(ctx("hotel"),{kind:"period_compare",dataset:"revenue",metric:{field:"amount",agg:"sum"},dateField:"revenue_date",periodA:{token:"this_month"},periodB:{token:"last_month"},breakdownBy:[],where:[]});expect(partial.periods?.note).toContain("7 days");expect(partial.periods?.note).toContain("30 days");});
});
