import { randomUUID } from "node:crypto";
import { AnalysisSpec as Schema, resolveDateToken, type AnalyticsService, type DataService, type MetadataStore, type RequestContext, type AnalysisSpec, type AnalysisResult, type Period } from "@cab/contracts";

const period=(p:Period,now:string)=>p.token?resolveDateToken(p.token,now):{start:p.start!,end:p.end!};
const days=(a:string,b:string)=>Math.round((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000)+1;
const range=(field:string,start:string,end:string)=>({field,op:"between" as const,value:[start,end]});

export function createAnalyticsService({data,metadata}:{data:DataService;metadata:MetadataStore}):AnalyticsService{
 return {async run(ctx,raw){const spec=Schema.parse(raw);const app=await metadata.getApp(ctx);if(ctx.appId!==app.appId)throw new Error("Cannot analyze another app");const ds=app.datasets.find(d=>d.name===spec.dataset);if(!ds)throw new Error(`Unknown dataset: ${spec.dataset}`);const metricField=ds.fields.find(f=>f.name===spec.metric.field);if(!metricField)throw new Error(`Unknown metric field: ${spec.metric.field}`);const dateField=spec.dateField??ds.timeField;
  if(spec.kind==="period_compare"){
   if(!dateField||!ds.fields.some(f=>f.name===dateField&&f.type==="date"))throw new Error("A date field is required for period comparison");const a=period(spec.periodA,ctx.now),b=period(spec.periodB,ctx.now),na=days(a.start,a.end),nb=days(b.start,b.end);const baseWhere=[...spec.where];const query=async(p:{start:string;end:string})=>data.query(ctx,{dataset:spec.dataset,select:[],where:[...baseWhere,range(dateField,p.start,p.end)],groupBy:spec.breakdownBy.map(field=>({field})),metrics:[{field:spec.metric.field,agg:spec.metric.agg,as:"value"}],orderBy:[],limit:500});
   const [qa,qb,baselineRows]=await Promise.all([query(a),query(b),data.query(ctx,{dataset:spec.dataset,select:[dateField],where:[...baseWhere,range(dateField,b.start,b.end)],groupBy:[],metrics:[],orderBy:[],limit:1})]);const sum=(r:typeof qa.rows)=>r.reduce((n,x)=>n+Number(x.value??0),0);const av=sum(qa.rows),bv=sum(qb.rows),abs=av-bv,pct=bv===0?null:abs/bv;const baselineEmpty=baselineRows.rowCount===0;const insufficient=baselineEmpty||(pct!==null&&Math.abs(pct)<=.02);let breakdown:NonNullable<AnalysisResult["breakdown"]>|undefined;
   if(spec.breakdownBy.length){const keys=new Set([...qa.rows,...qb.rows].map(r=>JSON.stringify(Object.fromEntries(spec.breakdownBy.map(k=>[k,r[k] as string|number|null])))));breakdown=[...keys].map(s=>{const key=JSON.parse(s) as Record<string,string|number|null>;const get=(rows:typeof qa.rows)=>rows.find(r=>spec.breakdownBy.every(k=>r[k]===key[k]));const va=Number(get(qa.rows)?.value??0),vb=Number(get(qb.rows)?.value??0),delta=va-vb;return {key,a:va,b:vb,abs:delta,pct:vb===0?null:delta/vb,shareOfChange:abs===0?null:delta/abs};});}
   const note=na===nb?undefined:`Period A is ${spec.periodA.token==="this_month"?`month-to-date (${na} days)`:na+" days"} vs ${spec.periodB.token==="last_month_to_date"?`month-to-date (${nb} days)`:nb+" days"}.`;
   return {resultId:randomUUID(),kind:spec.kind,dataset:spec.dataset,metric:spec.metric,periods:{a:{...a,days:na,value:av},b:{...b,days:nb,value:bv},note},absChange:abs,pctChange:pct,breakdown,evidence:[{id:qa.queryId,text:`${spec.metric.agg}(${spec.metric.field}) for period A`,value:av},{id:qb.queryId,text:`${spec.metric.agg}(${spec.metric.field}) for period B`,value:bv},{id:baselineRows.queryId,text:"Baseline row presence",value:baselineEmpty?0:1}],insufficientEvidence:insufficient,reason:insufficient?(baselineEmpty?"The baseline period has no matching rows.":"The measured change is within ±2%, too small to support a meaningful explanation."):undefined,provenance:{dataset:spec.dataset,queryIds:[qa.queryId,qb.queryId,baselineRows.queryId]}};
  }
  if(spec.kind==="trend"){
   if(!dateField)throw new Error("A date field is required for trend");const p=period(spec.period,ctx.now);const q=await data.query(ctx,{dataset:spec.dataset,where:[...spec.where,range(dateField,p.start,p.end)],groupBy:[{field:dateField,grain:spec.grain},...spec.breakdownBy.map(field=>({field}))],metrics:[{...spec.metric,as:"value"}],orderBy:[{field:dateField,direction:"asc"}],limit:500});return {resultId:randomUUID(),kind:spec.kind,dataset:spec.dataset,metric:spec.metric,series:q.rows.map(r=>({period:String(r[dateField]),value:Number(r.value??0),key:spec.breakdownBy.length?Object.fromEntries(spec.breakdownBy.map(k=>[k,r[k] as string|number|null])):undefined})),evidence:[{id:q.queryId,text:`Trend of ${spec.metric.field}`,value:q.rowCount}],insufficientEvidence:q.rowCount===0,reason:q.rowCount===0?"No rows match the requested trend period.":undefined,provenance:{dataset:spec.dataset,queryIds:[q.queryId]}};
  }
  const p=spec.period?period(spec.period,ctx.now):undefined;const q=await data.query(ctx,{dataset:spec.dataset,where:[...spec.where,...(p&&dateField?[range(dateField,p.start,p.end)]:[])],groupBy:[{field:spec.by}],metrics:[{...spec.metric,as:"value"}],orderBy:[{field:"value",direction:spec.direction}],limit:spec.limit});return {resultId:randomUUID(),kind:spec.kind,dataset:spec.dataset,metric:spec.metric,ranking:q.rows.map(r=>({key:r[spec.by] as string|number,value:Number(r.value??0)})),evidence:[{id:q.queryId,text:`Rank ${spec.by} by ${spec.metric.field}`,value:q.rowCount}],insufficientEvidence:q.rowCount===0,reason:q.rowCount===0?"No rows match the ranking request.":undefined,provenance:{dataset:spec.dataset,queryIds:[q.queryId]}};
 }};
}

export { createFakeAnalyticsService } from "./fake";
